# Generated by Django 2.2.3 on 2019-07-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refno', models.CharField(max_length=50, unique=True, verbose_name='Reference No')),
                ('slno', models.CharField(max_length=50, verbose_name='Serial No')),
                ('date', models.DateField(verbose_name='Entry Date')),
                ('mata_name', models.TextField(blank=True, verbose_name='Name of Materials')),
                ('manu_name', models.CharField(blank=True, max_length=50, verbose_name='Manufacturer Name')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='Batch No')),
                ('product', models.TextField(blank=True, verbose_name='Used in Product')),
                ('agent', models.CharField(blank=True, max_length=250, verbose_name='Local Agent')),
                ('mfgdate', models.DateField(blank=True, null=True, verbose_name='MFG Date')),
                ('expdate', models.DateField(blank=True, null=True, verbose_name='EXP Date')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('consumption', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('coa', models.FileField(blank=True, null=True, upload_to='pdf/coa', verbose_name='Certificate of Analysis')),
                ('msds', models.FileField(blank=True, null=True, upload_to='pdf/msds')),
                ('moa', models.FileField(blank=True, null=True, upload_to='pdf/moa', verbose_name='Method of Analysis')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farma_app.Unit')),
            ],
        ),
    ]
